spring:
  application:
    name: secure-doc-server
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    port: ${EMAIL_PORT}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 30000
          connectintimeout: 30000
          timeout: 30000
          auth: true
          starttls:
            enabled: true
            required: true
    verified:
      host: ${EMAIL_VERIFIED_HOST}
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: true
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:/data/schema.sql
      data-locations: classpath:/data/data.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: ${CONTAINER_PORT:8080}
  error:
    whitelabel:
      enabled: false
    path: /user/error